site_name: "James Glass | Technical Writing | Developer Enablement | AI-Driven Docs"
site_url: https://thewritingtimes.blog

theme:
  name: material
  font:
    text: Merriweather Sans
  logo: assets/james2.png
  favicon: assets/james1.png
  features:
    - navigation.tabs
    - navigation.footer
    - navigation.top
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.follow
    - navigation.expand
    - navigation.path
    - search.share
    - search.highlight
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide

  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep-purple

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep-orange

plugins:
  - search
  - blog

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details

nav:
  - Home: index.md

  - Background:
      - Experience: background/experience.md
      - Training and Development: background/training-and-development.md
      - PhD: background/phd.md
      - Masters:
          - Demographics and Twitter Usage: background/masters/demographics-and-twitter-usage.md
          - Google Glass: background/masters/google-glass.md
          - Paris Terror Attacks: background/masters/paris-terror-attacks.md
          - Thematic Analysis of Input Database: background/masters/thematic-analysis-of-input-database.md
      - BSc Mechatronics: background/bsc-mechatronics.md
      - BSc Screen Practice: background/bsc-screen-practice.md

  - Game Engine Docs:
      - Overview: game-docs-example/index.md
      - Onboarding:
          - Overview: game-docs-example/onboarding/onboarding-overview.md
          - New Starter Guide: game-docs-example/onboarding/new-starter-guide.md
          - First Week Checklist: game-docs-example/onboarding/first-week-checklist.md
          - Project Tour: game-docs-example/onboarding/project-tour.md
      - Core Concepts:
          - GameObjects and Components: game-docs-example/core/gameobjects-and-components.md
      - Getting Started:
          - Installation: game-docs-example/getting-started/installation.md
          - Project Setup: game-docs-example/getting-started/project-setup.md
          - First Scene: game-docs-example/getting-started/first-scene.md

  - AI Blog:
    - Overview: blog/index.md
    - Posts:
        - AI Agent Blog: blog/posts/2026-04-08-ai-agent-blog.md
        - Guide for Electrical CAD: blog/posts/2026-04-13-guide-for-electrical-cad .md
        - Get Started with Electrical Software: blog/posts/2026-04-20-get-started-with-electrical-software.md

  - Blog Examples:
      - Overview: examples/index.md
      - CAD Trends: examples/cad-trends.md
      - CAD Software: examples/cad-software.md
      - Start with elecworks: examples/start-with-elecworks.md
      - Divorce in Spain: examples/rdb-abogados:-divorce.md
      - Franchising in Spain: examples/rdb-abogados:-excel-in-franchising.md
      - NIE Numbers in Spain: examples/rdb-abogados:-nie-number.md

  - API Examples:
      - Online Order API: api-examples/online-order-api.md
      - Pulse API Reference: api-examples/pulse-api-reference.md

  - SQL Examples:
      - New York Restaurants: sql-examples/new-york-restaurants.md
      - SQLite: sql-examples/sqlite.md
      - Trends in Startups: sql-examples/trends-in-startups.md

  - Diagrams: diagrams.md

  - Dashboard:
      - Overview: dashboard/index.md
      - Dashboard Example One: dashboard/dashboard-example-one.md
      - Dashboard Example Two: dashboard/dashboard-example-two.md

  - References:
      - Overview: references/index.md
      - Quotes: quotes.md

extra:
  analytics:
    provider: google
    property: G-DFB5D1HK5Q
  social:
    - icon: material/linkedin
      link: https://www.linkedin.com/in/james-glass-phd-206b7b3/

extra_css:
  - assets/stylesheets/extra.css

copyright: "Copyright © 2025 James Glass"